### ISSUE TITLE
Bindgen ERROR: unsupported type `CXTypeKind(119)`

### ISSUE THREAD

**Issue by MabezDev** [fortanix/rust-mbedtls#61] opened 2019-10-07 11:39 UTC
```
$ clang --version

clang version 8.0.1 (tags/RELEASE_801/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

Is there a specific version of clang required to build this project?

**Comment by jethrogb** [comment] 2019-10-07 12:17
Unfortunately the version of bindgen used requires clang 3.8 or older right now. We're working on fixing this.

Closing as duplicate of #5.

**Closed by jethrogb** 2019-10-07 12:17 UTC

**Comment by jethrogb** [comment] 2021-03-11 18:48
Final PR: #152

**Comment by jethrogb** [comment] 2021-04-06 14:42
Fixed in #152
