### ISSUE TITLE
Build fails with bindgen errors

### ISSUE THREAD

**Issue by connorcl** [fortanix/rust-mbedtls#121] opened 2020-07-28 16:15 UTC
I've been trying to use this library in a `no_std` project, but the build of `mbedtls-sys-auto` always fails with a large number of Bindgen ERROR: unsupported type \`CXTypeKind(119)\` errors. I tried to make sure it wasn't the result of cross-compilation or a wrong selection of features by trying to include `mbedtls` as a dependency in an otherwise empty project (not `no_std`), but the build still fails with this same bindgen error.

**Comment by jethrogb** [comment] 2020-07-28 16:20
Duplicate of #5

**Closed by jethrogb** 2020-07-28 16:20 UTC

**Comment by jethrogb** [comment] 2021-03-11 18:49
Final PR: #152

**Comment by jethrogb** [comment] 2021-04-06 14:42
Fixed in #152
